[project]
name = 'Blockchain-Based-Retail-Supply-Chain-Transparency'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumer-information]
path = 'contracts/consumer-information.clar'
clarity_version = 2
epoch = 2.5

[contracts.ethical-sourcing]
path = 'contracts/ethical-sourcing.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-journey]
path = 'contracts/product-journey.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-journey_]
path = 'contracts/product-journey_.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-assurance]
path = 'contracts/quality-assurance.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-verification]
path = 'contracts/supplier-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
